### ISSUE TITLE
Support of 128x64 display and drawing

### ISSUE THREAD

**Issue by FabianNitsche** [iot-sas/SSD1306-Sharp#2]
Thanks for this library. I tried to use it for a SSD1306 display with resolution 128x64 and it did not work. I have a fix for that, however, I cannot test if it still works for the 128x32 displays. Additionally, I started implementing drawing. 

Are you interested in respective pull request?

**Comment by logicethos** [comment]
Yes thank you.  The library is a bit limited, as I wrote it for the single purpose of displaying IP address with the best font possible.

**Comment by FabianNitsche** [comment]
After quite some time searching for a library for easy access to the display. This was the fastest and easiest.

**Comment by FabianNitsche** [comment]
I will extend the drawing stuff before I commit a pull request. I think I can close this for now.
